### ISSUE TITLE
Specifying @Convert doesn't default to making a field persistent

### ISSUE THREAD

**Issue by mboapache** [datanucleus/datanucleus-api-jdo#109]
# JDO Converter Test Case

## Summary
PM.makePersistent runs into an exception when using a PC class with Convert annotation instead of metadata in a .jdo file.

## Details

This test case shows a runtime issue with a persistence capable class having a persistent field with a converter annotation.

Model class PCRect is a persistence capable class with two fields of type Point. Point is a simple class with two int fields x and y. Both point fields are mapped to a string of the form "x:y" in the database using a converter class PointToStringConverter.

The test case SimpleTest creates a PCRect instance with two Point instances and commits the transaction. 
When using annotations in the field declaration of the PCRect class, then method PersistenceManager.makePersistent 
throws an  IllegalArgumentException (see stacktrace below). 

The exception does not occur when using JDO metadata in a .jdo file (package.jdo) instead of using annotations in the PCRect class.

The branches [converter-annotation](https://github.com/mboapache/test-jdo/tree/converter-annotation) and [converter-metadata](https://github.com/mboapache/test-jdo/tree/converter-metadata) contain the test case showing this behaviour. The branch converter-annotation shows the exception.

## Stacktrace

```  
java.lang.IllegalArgumentException: out of field index :1 
    at mydomain.model.PCRect.dnCopyField(PCRect.java)
    at mydomain.model.PCRect.dnCopyFields(PCRect.java)
    at org.datanucleus.state.StateManagerImpl.saveFields(StateManagerImpl.java:5862)
    at org.datanucleus.state.StateManagerImpl.initialiseForPersistentNew(StateManagerImpl.java:495)
    at org.datanucleus.state.StateManagerImpl.initialiseForPersistentNew(StateManagerImpl.java:126)
    at org.datanucleus.state.ObjectProviderFactoryImpl.newForPersistentNew(ObjectProviderFactoryImpl.java:205)
    at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:2025)
    at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1869)
    at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1724)
    at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:715)
    at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:740)
    at org.datanucleus.test.SimpleTest.testSimple(SimpleTest.java:32)
```

**Comment by andyjefferson** [comment]
FWIW, if you add @Persistent to your field(s) the test passes. Why that is, is a different question ...

**Comment by mboapache** [comment]
Thanks for the feedback! I can confirm adding @Persistent makes the test case succeed. That allows me to continue on the corresponding JDO TCK test case.

I leave the issue open, for the need of adding @Persistent to make the field a persistent field.

**Comment by mboapache** [comment]
The field having the @Convert annotation was also annotated with @Column:
    @Convert(value = PointToStringConverter.class)
    @Column(name="LOWER_RIGHT")
    private Point lowerRight;
Does the same apply to @Column?

**Comment by andyjefferson** [comment]
I don't see why just putting `@Column` on a field of some unpersistable type should make it set the persistence modifier to PERSISTENT. The *converter* provides a way to persist a field of this (previously unknown, and not PersistenceCapable) type "Point", hence should default to persistable once the converter is provided.

Clearly there's loads of combinations I've never tested ...
