### ISSUE TITLE
Unable to call stored procedure following http://www.datanucleus.org/products/datanucleus/jdo/stored_procedures.html

### ISSUE THREAD

**Issue by DmitryLitvintsev** [datanucleus/datanucleus-api-jdo#17]
Hi, 

I am following recipe described here:

http://www.datanucleus.org/products/datanucleus/jdo/stored_procedures.html

I need to call stored procedure. I used postgresql RDBMS

The code snippet:
```
        PersistenceManager pm = pmf.getPersistenceManager();

        Transaction tx = pm.currentTransaction();

        try {

            tx.begin();

            Query query = pm.newQuery("STOREDPROC","foo");

            query.execute();

            tx.commit();

        } finally {

            try {

                rollbackIfActive(tx);

            } finally {

                pm.close();

            }

        }
```

results in stack:

javax.jdo.JDODataStoreException: Error encountered when extracting results for SQL query "foo"
        at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:543) ~[datanucleus-api-jdo-4.1.1.
jar:na]
        at org.datanucleus.api.jdo.JDOQuery.execute(JDOQuery.java:242) ~[datanucleus-api-jdo-4.1.1.jar:na]
        at org.dcache.services.billing.db.impl.datanucleus.DataNucleusBillingInfo.executeStoredProcedure(DataNucleusBillingInfo.java:275) ~[dc
ache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
        at org.dcache.services.billing.db.impl.datanucleus.DataNucleusBillingInfo.aggregateDaily(DataNucleusBillingInfo.java:263) ~[dcache-cor
e-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.2.6.RELEASE.jar:4.2.6.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.6.RELEASE.jar:4.2.6.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_25]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_25]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_25]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_25]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "CALL" 
postgresql log says:

```
2016-06-01 14:03:59.794 CDTERROR:  syntax error at or near "CALL" at character 1
2016-06-01 14:03:59.794 CDTSTATEMENT:  CALL foo()
```

postgresql does not support CALL to invoke procedures, it uses select. 

I understand that I could do something like

```Query query = pm.newQuery("javax.jdo.query.SQL","SELECT foo()");```

but then it won't work with Oracle for instance. Help?

**Comment by andyjefferson** [comment]
This is an ISSUE TRACKER where people raise ISSUES with TESTCASES, not a place to ask questions. Use the forum or StackOverflow for questions
